[package]
name = "syncthing_relay_server_ips"
version = "0.1.0"
edition = "2021"

[lib]
name = "syncthing_relay_server_ips"
path = "./src/main.rs"

[dependencies]
attohttpc = { version = "0.18.0", features = ["json"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }